

CREATE TABLE public."user2" (
                               id integer NOT NULL,
                               username VARCHAR(52)  NOT NULL,
                               password VARCHAR(52) NOT NULL,
                               email VARCHAR(52) NOT NULL,
                               role VARCHAR(52) NOT NULL,
);


ALTER TABLE public."user2" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_se
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY public."user2"
    ADD CONSTRAINT user_key PRIMARY KEY (id);



ALTER TABLE ONLY public."user2"
    ADD CONSTRAINT user_username_ke UNIQUE (username);

